// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5h_caVo8rRga-UMKR621VzfuuJ5KDk6k',
    appId: '1:163702977514:web:93c2b0446b9b3cd2f57893',
    messagingSenderId: '163702977514',
    projectId: 'jobank-bda58',
    authDomain: 'jobank-bda58.firebaseapp.com',
    storageBucket: 'jobank-bda58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzY7kUc6csNHhVOOFupp1SGAP1FxceZQ',
    appId: '1:163702977514:android:5c3f236f26615fcff57893',
    messagingSenderId: '163702977514',
    projectId: 'jobank-bda58',
    storageBucket: 'jobank-bda58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7BhU5tUgytz078FAIcpkaiAWV4ThL_ng',
    appId: '1:163702977514:ios:29d12fd34dd40c9cf57893',
    messagingSenderId: '163702977514',
    projectId: 'jobank-bda58',
    storageBucket: 'jobank-bda58.appspot.com',
    iosClientId: '163702977514-hsp008ieqdoks9jqg05mvq9bdb7jqkdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.jojo',
  );
}
